config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "schedules#index"
  resources :schedules #ルーティングを自動生成
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title,presence: true,length: {maximum: 20}
  validates :starting_date,presence: true
  validates :ending_date,presence: true
  validates :memo,length: {maximum: 500}
  
  validate :start_end_check

  def start_end_check
    if ending_date.blank? || starting_date.blank?
      errors.add(:base, "以下の空欄を入力してください。") 
    elsif self.ending_date < self.starting_date
      errors.add(:end_date, "は開始日より前の日付は登録できません。") 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  #予定一覧表示
  def index
    @schedules = Schedule.all 
    
  end

  #予定詳細表示
  def show
    @schedule = Schedule.find(params[:id])
  end

  #予定の作成
  def new
    @schedule = Schedule.new
  end 
  
  #予定の登録
  def create 
    #Scheduleモデルを初期化
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :starting_date, :ending_date, :is_all_day, :memo))
    #ScheduleモデルをDBへ保存
    if @schedule.save
       flash[:notice] = "新規スケジュールを作成しました" 
       redirect_to :schedules
    else
      flash.now[:alert] = "スケジュール作成に失敗しました"
      render :new,status: :unprocessable_entity
    end   
  end 
  
  #予定の編集
  def edit 
    @schedule = Schedule.find(params[:id])
  end 
  
  #予定の更新
  def update 
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      flash[:notice] = "スケジュールを編集しました" 
      redirect_to :schedules
    else
      flash.now[:alert] = "スケジュール編集に失敗しました"
      render 'edit',status: :unprocessable_entity
    end    
  end 
  
  #予定の削除
  def destroy 
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedules_path
  end   

  private
  def schedule_params
    params.require(:schedule).permit(:title,:starting_date,:ending_date,:memo,:is_all_day)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h1>スケジュールの編集</h1>
<%= render partial: 'shared/error' %>
<%= render partial: 'shared/partial' %>

<%= link_to '一覧へ戻る',schedules_path %>

app/views/schedules/index.html.erb
  <h1>スケジュール管理アプリ</h1>

    <div class="flash-notifications">
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: key) %>
    <% end %>
    </div>

  

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
  <% @schedules.each do |schedule|%>
  <tr>
    <td><%= schedule.id %></td>
    <td><%= schedule.title %></td>
    <td><%= schedule.starting_date.strftime('%Y/%m/%d') %></td>
    <td><%= schedule.ending_date.strftime('%Y/%m/%d') %></td>
    <td><% if schedule.is_all_day == true %>
    <%= "○" %>
    <% end %>
    </td>
    <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
    <td><%= link_to '詳細',schedule_path(schedule)%></td>
    <td><%= link_to '編集',edit_schedule_path(schedule)%></td>
    <td><%= link_to '削除',schedule_path(schedule),
    data: { turbo_method: 'delete', turbo_confirm: '予定を削除しますか？' } %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<p><%= link_to '新規スケジュール作成',new_schedule_path%></p>

<div class="FooterBody">
  <td>予定合計:<%= @schedules.count %><span>件</span></td>
  <td>今日の日付：<%= Date.current.strftime('%Y/%m/%d') %></td>
</div>

app/views/schedules/new.html.erb
<h1>新規スケジュール作成</h1>
<%= render partial: 'shared/error' %>
<%= render partial: 'shared/partial' %>




<%= link_to 'スケジュール一覧へ戻る',schedules_path %>

app/views/schedules/show.html.erb
<h3>スケジュール詳細</h3>

<%= link_to '予定を編集する',edit_schedule_path %>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.starting_date %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.ending_date %></td>
  </tr>
  <tr>
    <th>メモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><% if @schedule.is_all_day == true %>
    <%= "○" %>
    <% end %>
    </td>
  </tr>
</table>

<%= link_to '一覧へ戻る',schedules_path %>

app/views/shared/_error.html.erb
<% flash.each do |message_type, message| %>
    <div><%= message %></div>
<% end %>

app/views/shared/_partial.html.erb
<%= form_with model: @schedule do |f| %>
  <% if @schedule.errors.any? %>
    <div>
      <ul>
        <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div> 
<% end %>       
<table>
  <tr>
    <th><%= f.label :title ,"タイトル" %></th>
    <td><%= f.text_field :title %></td>
  </tr>
  
  <tr>
    <th><%= f.label :starting_date ,"開始日" %></th>
    <td><%= f.date_field :starting_date %></td>
  </tr>
  
  <tr>
    <th><%= f.label :ending_date ,"終了日" %></th>
    <td><%= f.date_field :ending_date %></td>
  </tr>
      
      

  <tr>
    <th><%= f.label :memo ,"メモ" %></th>
    <td><%= f.text_area :memo %></td>
  </tr>
      
  <tr>
    <th><%= f.label :is_all_day,"終日"%></th>
    <td><%= f.check_box :is_all_day, {}, "true", "false" %>
        
    <label>終日の場合はチェックを入れます</label></td>
  </tr>
        
    
</table>

    


    
<input type="submit">
    
<% end %>